### ISSUE TITLE
Investigate test execution reordering and @dataprovider

### ISSUE THREAD

**Issue by epdenouden** [epdenouden/phpunit#8]
This issue is for tracking https://github.com/sebastianbergmann/phpunit/issues/3246

Ping @reinholdfuereder

**Comment by reinholdfuereder** [comment]
@epdenouden Thanks for taking a closer look! Do you need anything from me?

**Comment by epdenouden** [comment]
closing this ticket as a duplicate of https://github.com/sebastianbergmann/phpunit/issues/3396
